"""Tests for bond-length validation.

Two halves, deliberately.

The synthetic half places every atom by hand so that each test controls exactly one bond and a
failure names the defect class it broke. The calibration half runs the validator over the six real
fixtures in ``tests/data/structures/`` and over fresh ``dodo.rebuild()`` output, which is the only
way to know whether the tolerances land anywhere useful. Both are needed: a synthetic structure
has no cis-prolines, no unmodelled residues, no strained refinement and no experimental-versus-
predicted systematic offset, so the specific way a bond validator fails -- hundreds of findings on
perfectly good input -- is invisible without real data.

Every calibration number asserted here was measured, and the measurement is in the assertion
message so that a future reader can tell drift from breakage.
"""

from __future__ import annotations

import math
import time
from collections.abc import Mapping, Sequence
from pathlib import Path

import numpy as np
import pytest
from scipy.spatial.transform import Rotation

from dodo.constants import CA_CA_BOND_LENGTH
from dodo.exceptions import GeometryError
from dodo.io import read_structure
from dodo.structure import Structure
from dodo.validate.bonds import (
    DEFAULT_ABSOLUTE_TOLERANCE,
    DEFAULT_CA_CA_TOLERANCE,
    DEFAULT_TOLERANCE_SIGMA,
    BondReport,
    validate_bonds,
)
from dodo.validate.reference import (
    BOND_CUTOFF,
    CA_CA_SHORT_LENGTH,
    CA_CA_TRANS_LENGTH,
    PEPTIDE_BOND_LENGTH,
    RESIDUE_BONDS,
)

DATA = Path(__file__).resolve().parents[1] / "data" / "structures"

# ---------------------------------------------------------------------------
# Synthetic structure builder
# ---------------------------------------------------------------------------

#: One residue's atoms: name -> coordinate.
AtomSpec = Mapping[str, Sequence[float]]

#: One residue: (residue name, atoms, chain id, residue number).
ResidueSpec = tuple[str, AtomSpec, str, int]

#: Element inferred from an atom name for the synthetic builder. Only the first letter matters
#: here, and the real readers do the same thing for files with no element column.
_ELEMENTS = {"N": "N", "C": "C", "O": "O", "S": "S", "SE": "SE"}


def build(residues: Sequence[ResidueSpec]) -> Structure:
    """Assemble a structure from explicitly placed atoms.

    Coordinates in these tests are written out or derived from the reference table rather than
    generated by DODO, because the point is to control exactly which bonds are right and which
    are wrong.
    """
    xyz: list[Sequence[float]] = []
    names: list[str] = []
    elements: list[str] = []
    residue_names: list[str] = []
    residue_numbers: list[int] = []
    chain_ids: list[str] = []
    for residue_name, atoms, chain_id, number in residues:
        for atom_name, position in atoms.items():
            xyz.append(position)
            names.append(atom_name)
            elements.append(_ELEMENTS.get(atom_name[:2], _ELEMENTS.get(atom_name[:1], "C")))
            residue_names.append(residue_name)
            residue_numbers.append(number)
            chain_ids.append(chain_id)
    return Structure.from_atom_records(
        xyz=np.array(xyz, dtype=np.float64),
        atom_name=names,
        element=elements,
        residue_name=residue_names,
        residue_number=residue_numbers,
        chain_id=chain_ids,
        source="synthetic",
    )


def reference_length(residue: str, atom_a: str, atom_b: str) -> float:
    """Return the reference mean length of one bond, in Angstroms."""
    return RESIDUE_BONDS[residue][tuple(sorted((atom_a, atom_b)))][0]  # type: ignore[index]


def accepted_window(
    residue: str,
    atom_a: str,
    atom_b: str,
    *,
    sigma: float = DEFAULT_TOLERANCE_SIGMA,
    floor: float = DEFAULT_ABSOLUTE_TOLERANCE,
) -> tuple[float, float]:
    """Return the window :func:`validate_bonds` accepts for one bond, recomputed here."""
    _, sd, _, p_low, p_high = RESIDUE_BONDS[residue][tuple(sorted((atom_a, atom_b)))]  # type: ignore[index]
    slack = max(sigma * sd, floor)
    return p_low - slack, p_high + slack


def carbonyl_oxygen(carbon: Sequence[float], length: float, *, sign: float = 1.0) -> list[float]:
    """Place an oxygen on a carbon whose bond to CA runs along +x, at a CA-C-O angle of 120 deg.

    Not perpendicular, deliberately: perpendicular puts the oxygen 1.96 A from the alpha carbon,
    just inside the 1.90 A bonding cutoff plus rounding, which would make the unexpected-contact
    tests fragile for no reason. At 120 degrees it sits 2.39 A away.
    """
    return [
        carbon[0] + length * math.cos(math.radians(60.0)),
        carbon[1] + sign * length * math.sin(math.radians(60.0)),
        carbon[2],
    ]


def glycine(origin: Sequence[float] = (0.0, 0.0, 0.0)) -> AtomSpec:
    """Return a glycine whose every reference bond is exactly its measured mean.

    Glycine is the simplest complete residue -- four atoms, no ring, no side chain -- so it can be
    embedded in 3D with every bond exactly right, which makes it the baseline for "the validator
    must not flag correct geometry".
    """
    x, y, z = origin
    n = reference_length("GLY", "CA", "N")
    ca_c = reference_length("GLY", "C", "CA")
    carbon = [x + ca_c, y, z]
    return {
        "N": [x - n, y, z],
        "CA": [x, y, z],
        "C": carbon,
        "O": carbonyl_oxygen(carbon, reference_length("GLY", "C", "O")),
    }


#: Residue types whose reference bond graph is a tree, so a single residue can be embedded in 3D
#: with every bond exactly at its measured mean. The five excluded types have rings (PRO's
#: pyrrolidine, the four aromatics' side chains), and a ring cannot be built bond-by-bond from a
#: spanning tree -- the closing bond comes out wrong. Ring geometry is covered instead by the
#: fixture tests, which contain 3,000-odd real rings between them.
ACYCLIC_RESIDUES = tuple(sorted(set(RESIDUE_BONDS) - {"PRO", "HIS", "PHE", "TYR", "TRP"}))

#: Bond angle used when placing an atom relative to its parent's own bond, in degrees. Roughly
#: tetrahedral, which is what real geometry does. Placing atoms along free axes instead produces a
#: collinear chain, and then the second oxygen of a carboxylate has nowhere to go that is more than
#: 1.77 A from the first -- inside the bonding cutoff, which would trip the unexpected-contact
#: check and make these tests report the wrong thing.
_PLACEMENT_ANGLE = 112.0

#: Azimuths tried around the parent bond, in degrees.
_PLACEMENT_AZIMUTHS = tuple(range(0, 360, 20))


def _perpendicular(vector: np.ndarray) -> np.ndarray:
    """Any unit vector perpendicular to ``vector``."""
    axis = np.eye(3)[int(np.argmin(np.abs(vector)))]
    perpendicular = np.cross(vector, axis)
    return perpendicular / np.linalg.norm(perpendicular)


def _candidate_positions(
    parent: np.ndarray, incoming: np.ndarray | None, length: float
) -> list[np.ndarray]:
    """Positions ``length`` from ``parent`` at a realistic bond angle to ``incoming``."""
    if incoming is None:
        # The root has no bond to make an angle with, so try the coordinate axes.
        return [
            parent + length * direction for direction in np.concatenate([np.eye(3), -np.eye(3)])
        ]
    axial = math.cos(math.radians(180.0 - _PLACEMENT_ANGLE))
    radial = math.sin(math.radians(180.0 - _PLACEMENT_ANGLE))
    e2 = _perpendicular(incoming)
    e3 = np.cross(incoming, e2)
    return [
        parent
        + length
        * (
            axial * incoming
            + radial * (math.cos(math.radians(phi)) * e2 + math.sin(math.radians(phi)) * e3)
        )
        for phi in _PLACEMENT_AZIMUTHS
    ]


def residue_at_reference(name: str) -> AtomSpec:
    """Embed one acyclic residue with every reference bond at exactly its measured mean.

    Placement walks a spanning tree of the residue's bond graph outward from CA. Each atom goes at
    exactly its reference distance from its parent, at a tetrahedral angle to the parent's own
    bond, on whichever azimuth maximizes its distance to the nearest already-placed non-bonded
    atom. The clearance maximization matters: a residue with correct bond lengths but atoms on top
    of each other would trip the unexpected-contact check, and the test would then pass or fail for
    the wrong reason.
    """
    table = RESIDUE_BONDS[name]
    neighbours: dict[str, list[tuple[str, float]]] = {}
    for (atom_a, atom_b), (mean, *_rest) in table.items():
        if "OXT" in (atom_a, atom_b):  # a C-terminal atom; not part of the residue body
            continue
        neighbours.setdefault(atom_a, []).append((atom_b, mean))
        neighbours.setdefault(atom_b, []).append((atom_a, mean))

    placed: dict[str, np.ndarray] = {"CA": np.zeros(3)}
    incoming: dict[str, np.ndarray | None] = {"CA": None}
    order = ["CA"]
    bonded: set[frozenset[str]] = {frozenset((a, b)) for a, b in table}
    while order:
        parent = order.pop(0)
        for child, length in sorted(neighbours.get(parent, [])):
            if child in placed:
                continue
            best: tuple[float, np.ndarray] | None = None
            for candidate in _candidate_positions(placed[parent], incoming[parent], length):
                clearance = min(
                    (
                        float(np.linalg.norm(candidate - position))
                        for other, position in placed.items()
                        if frozenset((child, other)) not in bonded
                    ),
                    default=float("inf"),
                )
                if best is None or clearance > best[0]:
                    best = (clearance, candidate)
            assert best is not None, f"{name}: nowhere to put {child}"
            assert best[0] > BOND_CUTOFF, (
                f"{name}: {child} could only be placed {best[0]:.3f} A from a non-bonded atom, "
                f"inside the {BOND_CUTOFF} A bonding cutoff"
            )
            placed[child] = best[1]
            direction = best[1] - placed[parent]
            incoming[child] = direction / np.linalg.norm(direction)
            order.append(child)

    missing = {atom for pair in table for atom in pair} - set(placed) - {"OXT"}
    assert not missing, f"{name}: failed to place {sorted(missing)}"
    return {atom: position.tolist() for atom, position in sorted(placed.items())}


def ca_only_chain(
    n_residues: int = 8,
    *,
    spacing: float = CA_CA_BOND_LENGTH,
    chain: str = "A",
    first_number: int = 1,
) -> Structure:
    """Return a CA-only chain, which is exactly what a rebuilt region looks like.

    Built as a flat zig-zag rather than a straight line so that no two alpha carbons come near
    each other, which keeps these tests about bond lengths.
    """
    residues: list[ResidueSpec] = []
    step = math.sqrt(spacing**2 / 2.0)
    for i in range(n_residues):
        residues.append(("ALA", {"CA": [i * step, step * (i % 2), 0.0]}, chain, first_number + i))
    return build(residues)


def move_atom(structure: Structure, residue: int, atom: str, position: Sequence[float]) -> None:
    """Move one named atom of one residue, in place."""
    atoms = structure.atom_slice_for_residues(residue, residue + 1)
    names = [str(name) for name in structure.atom_name[atoms]]
    structure.xyz[atoms.start + names.index(atom)] = np.asarray(position, dtype=np.float64)


def stretch_bond(
    structure: Structure, residue: int, anchor: str, moved: str, length: float
) -> None:
    """Place ``moved`` at ``length`` Angstroms from ``anchor``, keeping its direction."""
    atoms = structure.atom_slice_for_residues(residue, residue + 1)
    names = [str(name) for name in structure.atom_name[atoms]]
    origin = structure.xyz[atoms.start + names.index(anchor)]
    current = structure.xyz[atoms.start + names.index(moved)]
    direction = current - origin
    direction = direction / np.linalg.norm(direction)
    structure.xyz[atoms.start + names.index(moved)] = origin + direction * length


# ---------------------------------------------------------------------------
# CA-only regions: the load-bearing case for everything DODO builds
# ---------------------------------------------------------------------------


def test_clean_ca_only_trace_is_valid() -> None:
    structure = ca_only_chain(10)
    report = validate_bonds(structure)
    assert report.ok, report.describe()
    assert bool(report) is True
    assert report.n_ca_ca_checked == 9
    assert report.n_intra_checked == 0
    assert report.n_peptide_checked == 0
    assert report.n_ca_only_residues == 10


def test_ca_only_region_never_reports_a_missing_atom() -> None:
    """The single most important exclusion: a rebuilt region legitimately has only alpha carbons.

    Without it, every rebuilt residue produces findings for N, C and O -- 334 on a rebuilt
    dnmt3a -- and the report is useless.
    """
    report = validate_bonds(ca_only_chain(50))
    assert report.of_kind("missing_atom") == ()
    assert any("alpha carbon and nothing else" in note for note in report.notes)


def test_stretched_ca_ca_bond_is_reported_with_both_residues() -> None:
    structure = ca_only_chain(5)
    structure.xyz[structure.ca_indices[2]] += np.array([2.0, 0.0, 0.0])
    report = validate_bonds(structure)
    violations = report.of_class("ca_ca")
    assert len(violations) == 2, report.describe()
    first = violations[0]
    assert first.kind == "bond_length"
    assert first.residue_labels == ("A:ALA2", "A:ALA3")
    assert first.atoms == ("CA", "CA")
    assert f"{first.measured:.3f}" in first.message
    assert first.message.endswith(".")
    assert first.overshoot > 0.0


def test_coincident_alpha_carbons_are_named_as_such() -> None:
    """v1's own output contains two CA-CA bonds of exactly 0.000 A. That must never be silent."""
    structure = ca_only_chain(4)
    structure.xyz[structure.ca_indices[2]] = structure.xyz[structure.ca_indices[1]]
    report = validate_bonds(structure)
    messages = [v.message for v in report.of_class("ca_ca")]
    assert any("same point" in message for message in messages), messages


def test_rebuilt_ca_ca_bonds_are_held_to_the_length_dodo_builds_to() -> None:
    """A rebuilt region is checked against 3.81 A; preserved geometry gets the wider window.

    The distance used, 3.35 A, is inside the union of the two reference populations (so it passes
    as preserved input) and outside 3.81 +/- 0.20 (so it fails as rebuilt output).
    """
    from dodo.structure import Domain, DomainKind, Span

    distance = 3.35
    assert CA_CA_SHORT_LENGTH - DEFAULT_CA_CA_TOLERANCE < distance < CA_CA_TRANS_LENGTH
    assert abs(distance - CA_CA_BOND_LENGTH) > DEFAULT_CA_CA_TOLERANCE

    structure = ca_only_chain(4, spacing=distance)
    assert validate_bonds(structure).ok, "preserved CA-only geometry inside both populations"

    structure.chains[0].domains.append(
        Domain(structure=structure, span=Span(0, 4), kind=DomainKind.IDR, rebuilt=True)
    )
    report = validate_bonds(structure)
    assert len(report.of_class("ca_ca")) == 3, report.describe()
    assert report.of_provenance("rebuilt") == report.violations


# ---------------------------------------------------------------------------
# Intra-residue bonds
# ---------------------------------------------------------------------------


def test_residue_at_reference_geometry_is_valid() -> None:
    report = validate_bonds(build([("GLY", glycine(), "A", 1)]))
    assert report.ok, report.describe()
    assert report.n_intra_checked == len(RESIDUE_BONDS["GLY"]) - 1  # OXT is absent


def test_stretched_intra_residue_bond_names_the_bond_and_the_range() -> None:
    structure = build([("GLY", glycine(), "A", 7)])
    stretch_bond(structure, 0, "C", "O", 1.75)
    report = validate_bonds(structure)
    assert len(report.violations) == 1, report.describe()
    violation = report.violations[0]
    assert violation.kind == "bond_length"
    assert violation.bond_class == "intra_residue"
    assert violation.atoms == ("C", "O")
    assert violation.residue_labels == ("A:GLY7",)
    assert violation.measured == pytest.approx(1.75, abs=1e-6)
    assert violation.expected == pytest.approx(reference_length("GLY", "C", "O"), abs=1e-9)
    assert "A:GLY7" in violation.message
    assert "1.750" in violation.message
    assert violation.message.endswith(".")
    assert violation.deviation_sigma > 6.0


def test_tolerance_window_edges_are_respected() -> None:
    """Just inside the accepted window passes; just outside it does not.

    The window is recomputed here from the reference table rather than hardcoded, so this test
    tracks the tolerance definition instead of pinning a magic number.
    """
    low, high = accepted_window("GLY", "C", "O")
    for length, expected_ok in ((high - 1e-4, True), (high + 1e-3, False), (low - 1e-3, False)):
        structure = build([("GLY", glycine(), "A", 1)])
        stretch_bond(structure, 0, "C", "O", length)
        report = validate_bonds(structure)
        assert report.ok is expected_ok, f"{length:.4f} A against {low:.4f}-{high:.4f}"


def test_absolute_tolerance_is_a_floor_not_a_replacement() -> None:
    """Check that the floor applies with the sigma term switched off.

    The floor is what protects the tightest reference distributions from becoming unreasonably
    strict, so it has to be a floor and not a replacement.
    """
    _, high = accepted_window("GLY", "C", "O", sigma=0.0)
    inside = build([("GLY", glycine(), "A", 1)])
    stretch_bond(inside, 0, "C", "O", high - 1e-4)
    assert validate_bonds(inside, tolerance_sigma=0.0).ok

    outside = build([("GLY", glycine(), "A", 1)])
    stretch_bond(outside, 0, "C", "O", high + 0.01)
    assert not validate_bonds(outside, tolerance_sigma=0.0).ok
    # And the floor is doing the work: with no floor either, the same bond is far outside.
    assert not validate_bonds(inside, tolerance_sigma=0.0, absolute_tolerance=1e-6).ok


@pytest.mark.parametrize("name", ACYCLIC_RESIDUES)
def test_every_acyclic_residue_type_at_reference_geometry_is_clean(name: str) -> None:
    """No residue type, side chains included, may be flagged when built to the reference.

    This is the false-positive guard for the intra-residue table itself: 15 residue types and
    every one of their bonds, checked against the very numbers they were built from.
    """
    report = validate_bonds(build([(name, residue_at_reference(name), "A", 1)]))
    assert report.ok, report.describe()
    assert report.n_intra_checked == len(RESIDUE_BONDS[name]) - 1  # OXT is absent


@pytest.mark.parametrize(
    ("residue", "anchor", "moved"),
    [
        ("LYS", "CE", "NZ"),  # four bonds out along the side chain
        ("ARG", "CZ", "NH2"),  # the guanidinium tip
        ("MET", "SD", "CE"),  # a sulfur bond, whose reference length is 1.79 not 1.53
        ("THR", "CB", "OG1"),  # a hydroxyl
        ("ILE", "CG1", "CD1"),  # a branched aliphatic terminus
    ],
)
def test_side_chain_bonds_are_checked_not_just_the_backbone(
    residue: str, anchor: str, moved: str
) -> None:
    """The explicit ask: every bond, not just the backbone."""
    structure = build([(residue, residue_at_reference(residue), "A", 11)])
    _, high = accepted_window(residue, anchor, moved)
    stretch_bond(structure, 0, anchor, moved, high + 0.1)
    report = validate_bonds(structure)
    assert len(report.violations) == 1, report.describe()
    violation = report.violations[0]
    assert violation.atoms == tuple(sorted((anchor, moved)))
    assert violation.bond_class == "intra_residue"
    assert f"A:{residue}11" in violation.message


# ---------------------------------------------------------------------------
# Missing atoms, and the residues that are allowed to be incomplete
# ---------------------------------------------------------------------------


def test_incomplete_side_chain_reports_every_absent_atom() -> None:
    """A residue with side-chain atoms but not all of them is genuinely incomplete."""
    partial_lysine = {
        "N": [-1.4642, 0.0, 0.0],
        "CA": [0.0, 0.0, 0.0],
        "C": [1.5347, 0.0, 0.0],
        "O": [2.1, 1.07, 0.0],
        "CB": [0.0, 1.5372, 0.0],
        "CG": [0.0, 3.07, 0.0],
    }
    report = validate_bonds(build([("LYS", partial_lysine, "A", 42)]))
    missing = {v.atoms[0] for v in report.of_kind("missing_atom")}
    assert missing == {"CD", "CE", "NZ"}, report.describe()
    for violation in report.of_kind("missing_atom"):
        assert "A:LYS42" in violation.message
        assert violation.message.endswith(".")


def test_backbone_only_residue_is_not_called_incomplete() -> None:
    """DODO's next priority places backbone atoms in rebuilt regions with no side chains.

    Measured: without this exemption a backbone-only version of a rebuilt dnmt3a reports 2,323
    missing atoms, all of them noise.
    """
    backbone = {"N": [-1.4642, 0.0, 0.0], "CA": [0.0, 0.0, 0.0], "C": [1.5347, 0.0, 0.0]}
    backbone["O"] = carbonyl_oxygen(backbone["C"], reference_length("LYS", "C", "O"))
    report = validate_bonds(build([("LYS", backbone, "A", 5)]))
    assert report.of_kind("missing_atom") == (), report.describe()
    assert report.n_partial_residues == 1
    assert any("no side chain beyond CB" in note for note in report.notes)


def test_glycine_backbone_is_complete_not_partial() -> None:
    """GLY has no side chain to be missing, so it must not be counted as partially built."""
    report = validate_bonds(build([("GLY", glycine(), "A", 1)]))
    assert report.n_partial_residues == 0
    assert report.of_kind("missing_atom") == ()


def test_oxt_is_never_reported_missing_but_is_checked_when_present() -> None:
    """OXT exists once per chain. Demanding it everywhere would flag every other residue."""
    report = validate_bonds(build([("GLY", glycine(), "A", 1)]))
    assert "OXT" not in {v.atoms[0] for v in report.of_kind("missing_atom")}

    atoms = dict(glycine())
    oxt = reference_length("GLY", "C", "OXT")
    atoms["OXT"] = carbonyl_oxygen(atoms["C"], oxt, sign=-1.0)
    assert validate_bonds(build([("GLY", atoms, "A", 1)])).ok

    atoms["OXT"] = [atoms["C"][0] + 1.8, 0.6, 0.0]
    stretched = validate_bonds(build([("GLY", atoms, "A", 1)]))
    assert any(v.atoms == ("C", "OXT") for v in stretched.violations), stretched.describe()


def test_residue_with_one_non_ca_atom_is_incomplete_not_rebuilt() -> None:
    """CA-only means one atom AND that atom is the alpha carbon; anything else is incomplete."""
    report = validate_bonds(build([("GLY", {"N": [0.0, 0.0, 0.0]}, "A", 1)]))
    assert report.n_ca_only_residues == 0
    assert {v.atoms[0] for v in report.of_kind("missing_atom")} == {"C", "CA", "O"}


# ---------------------------------------------------------------------------
# Unexpected contacts
# ---------------------------------------------------------------------------


def test_atoms_placed_on_top_of_each_other_are_reported() -> None:
    atoms = dict(glycine())
    # Put the carbonyl oxygen 1.40 A from the amide nitrogen, which is not a bond of any residue.
    # Its own C-O bond is stretched too, and that is reported separately -- one finding per defect.
    atoms["O"] = [atoms["N"][0], 1.40, 0.0]
    report = validate_bonds(build([("GLY", atoms, "A", 3)]))
    contacts = report.of_kind("unexpected_contact")
    assert len(contacts) == 1, report.describe()
    assert set(contacts[0].atoms) == {"N", "O"}
    assert contacts[0].measured < BOND_CUTOFF
    assert "A:GLY3" in contacts[0].message
    assert "on top of each other" in contacts[0].message


def test_hydrogens_do_not_produce_unexpected_contacts() -> None:
    """Check that hydrogens are skipped by the unexpected-contact search.

    The reference table has no hydrogen bonds, so an X-H bond at 1.0 A would be reported as a
    coincidence -- one finding per hydrogen. DODO's readers drop hydrogens, but a hand-built
    Structure can still carry them.
    """
    atoms = dict(glycine())
    atoms["HA"] = [0.0, 1.0, 0.0]
    structure = build([("GLY", atoms, "A", 1)])
    structure.element[list(structure.atom_name).index("HA")] = "H"
    assert validate_bonds(structure).of_kind("unexpected_contact") == ()


def test_bonded_pairs_are_not_unexpected_contacts() -> None:
    """Every real bond is inside the cutoff, so a naive version of this check flags all of them."""
    report = validate_bonds(read_structure(DATA / "arf19.pdb"))
    assert report.of_kind("unexpected_contact") == (), report.describe()


# ---------------------------------------------------------------------------
# Inter-residue bonds
# ---------------------------------------------------------------------------


def two_glycines(*, peptide: float = PEPTIDE_BOND_LENGTH, ca_ca: float | None = None) -> Structure:
    """Two glycines joined by a peptide bond of a given length.

    When ``ca_ca`` is given the second residue is rotated about the peptide nitrogen so that the
    virtual CA-CA distance takes that value while the C-N bond keeps its length -- which is what a
    cis peptide is.
    """
    first = dict(glycine())
    n_ca = reference_length("GLY", "CA", "N")
    nitrogen = np.array([first["C"][0] + peptide, 0.0, 0.0])
    if ca_ca is None:
        alpha = nitrogen + np.array([n_ca, 0.0, 0.0])
    else:
        # Solve for the angle at N that puts CA(2) at the requested distance from CA(1).
        span = nitrogen[0] - first["CA"][0]
        cosine = (span**2 + n_ca**2 - ca_ca**2) / (2 * span * n_ca)
        angle = math.acos(max(-1.0, min(1.0, cosine)))
        # The angle is measured at N from the direction back toward CA(1), which is -x, so the
        # x component is negated. Getting that backwards silently produces a different distance.
        alpha = nitrogen + np.array([-n_ca * math.cos(angle), n_ca * math.sin(angle), 0.0])
    # The rest of residue 2 is built in the frame of its own N-CA bond rather than along +x, so
    # that a cis geometry does not fold its carbonyl back on top of its own nitrogen.
    forward = alpha - nitrogen
    forward = forward / np.linalg.norm(forward)
    sideways = np.cross(forward, np.array([0.0, 0.0, 1.0]))
    sideways = sideways / np.linalg.norm(sideways)
    carbon = alpha + reference_length("GLY", "C", "CA") * forward
    c_o = reference_length("GLY", "C", "O")
    oxygen = carbon + c_o * (
        math.cos(math.radians(60.0)) * forward + math.sin(math.radians(60.0)) * sideways
    )
    second = {
        "N": nitrogen.tolist(),
        "CA": alpha.tolist(),
        "C": carbon.tolist(),
        "O": oxygen.tolist(),
    }
    return build([("GLY", first, "A", 1), ("GLY", second, "A", 2)])


def test_clean_peptide_bond_is_valid_and_ca_ca_is_skipped() -> None:
    report = validate_bonds(two_glycines())
    assert report.ok, report.describe()
    assert report.n_peptide_checked == 1
    # The virtual bond is a surrogate for the real one, so where the real one exists it is what
    # gets checked.
    assert report.n_ca_ca_checked == 0
    assert report.n_ca_ca_skipped_peptide == 1


def test_stretched_peptide_bond_is_reported() -> None:
    report = validate_bonds(two_glycines(peptide=1.45))
    peptide = report.of_class("peptide")
    assert len(peptide) == 1, report.describe()
    assert peptide[0].kind == "bond_length"
    assert peptide[0].atoms == ("C", "N")
    assert peptide[0].residue_labels == ("A:GLY1", "A:GLY2")
    assert "1.450" in peptide[0].message


def test_cis_peptide_is_not_reported_but_can_be() -> None:
    """Check that a cis peptide is not a finding by default, and is one on request.

    A cis peptide puts CA-CA near 3.19 A with a perfect C-N bond. Real structures are full of them
    -- 26% of p300's pairs deviate from 3.81 A by more than 0.15 A -- so the default must not flag
    them, and a caller who wants to see them must be able to.
    """
    structure = two_glycines(ca_ca=2.95)
    assert validate_bonds(structure).ok, validate_bonds(structure).describe()

    strict = validate_bonds(structure, strict_ca_ca=True)
    assert len(strict.of_class("ca_ca")) == 1
    assert strict.n_ca_ca_checked == 1


def test_broken_chain_between_consecutive_numbers_is_its_own_finding() -> None:
    report = validate_bonds(two_glycines(peptide=20.0))
    breaks = report.of_kind("chain_break")
    assert len(breaks) == 1, report.describe()
    assert breaks[0].residue_labels == ("A:GLY1", "A:GLY2")
    assert "20.000" in breaks[0].message
    assert f"{BOND_CUTOFF:.2f}" in breaks[0].message
    # It is not also reported as a stretched bond: one defect, one finding.
    assert report.of_kind("bond_length") == ()


def test_numbering_gap_is_noted_not_flagged() -> None:
    """Check that a numbering gap suppresses the inter-residue checks.

    Residues either side of an unmodelled stretch are not chemically adjacent, so neither their
    peptide bond nor their CA-CA distance means anything.
    """
    first = dict(glycine())
    second = dict(glycine((40.0, 0.0, 0.0)))
    report = validate_bonds(build([("GLY", first, "A", 10), ("GLY", second, "A", 25)]))
    assert report.ok, report.describe()
    assert report.n_sequence_gaps == 1
    assert any("not consecutive in the deposited numbering" in note for note in report.notes)


def test_insertion_codes_are_consecutive_not_a_gap() -> None:
    """Check that an insertion code does not read as a chain break.

    Residues 10 and 10A are adjacent in the polymer, so treating equal numbering as a gap would
    skip every bond around an insertion.
    """
    structure = two_glycines()
    structure.residue_number[1] = structure.residue_number[0]
    structure.insertion_code[1] = "A"
    report = validate_bonds(structure)
    assert report.n_sequence_gaps == 0
    assert report.n_peptide_checked == 1


def test_separate_chains_are_never_bonded() -> None:
    first = dict(glycine())
    second = dict(glycine((50.0, 0.0, 0.0)))
    report = validate_bonds(build([("GLY", first, "A", 1), ("GLY", second, "B", 1)]))
    assert report.ok, report.describe()
    assert report.n_peptide_checked == 0
    assert report.n_ca_ca_checked == 0


def test_folded_to_rebuilt_boundary_is_checked_on_its_ca_ca_bond() -> None:
    """Check the junction between an all-atom stretch and a CA-only one.

    It is a real chain connection, and the CA-CA virtual bond is the only evidence available
    there, since the rebuilt side has no N to bond to.
    """
    first = dict(glycine())
    structure = build(
        [
            ("GLY", first, "A", 1),
            ("ALA", {"CA": [first["CA"][0] + 9.0, 0.0, 0.0]}, "A", 2),
        ]
    )
    report = validate_bonds(structure)
    assert report.n_ca_ca_checked == 1
    assert len(report.of_class("ca_ca")) == 1
    assert report.of_kind("missing_atom") == ()


# ---------------------------------------------------------------------------
# Modified residues, and coordinates that are not numbers
# ---------------------------------------------------------------------------


def test_modified_residue_is_noted_not_flagged() -> None:
    """DODO keeps MSE on purpose: dropping it fabricates a phantom chain break."""
    selenomethionine = {
        "N": [-1.46, 0.0, 0.0],
        "CA": [0.0, 0.0, 0.0],
        "C": [1.53, 0.0, 0.0],
        "O": [2.1, 1.07, 0.0],
        "CB": [0.0, 1.53, 0.0],
        "CG": [0.0, 3.06, 0.6],
        "SE": [0.0, 4.5, 1.9],
        "CE": [0.0, 6.4, 2.4],
    }
    report = validate_bonds(build([("MSE", selenomethionine, "A", 88)]))
    assert report.ok, report.describe()
    assert report.n_unknown_residues == 1
    assert any("MSE x1" in note for note in report.notes)
    assert any("noted, not flagged" in note for note in report.notes)


def test_non_finite_coordinate_is_reported_not_raised() -> None:
    structure = build([("GLY", glycine(), "A", 1)])
    structure.xyz[2] = np.array([np.nan, 0.0, 0.0])
    report = validate_bonds(structure)
    non_finite = report.of_kind("non_finite")
    assert len(non_finite) == 1
    assert non_finite[0].atoms == ("C",)
    assert math.isnan(non_finite[0].measured)
    assert math.isinf(non_finite[0].overshoot)
    # No bond involving the NaN atom is reported with a meaningless measured value.
    assert all(math.isfinite(v.measured) for v in report.violations if v.kind == "bond_length")


# ---------------------------------------------------------------------------
# Report surface
# ---------------------------------------------------------------------------


def broken_structure() -> Structure:
    """Return a CA-only trace with two displaced residues, so four virtual bonds are wrong."""
    structure = ca_only_chain(8)
    structure.xyz[structure.ca_indices[2]] += np.array([4.0, 0.0, 0.0])
    structure.xyz[structure.ca_indices[6]] -= np.array([0.0, 3.0, 1.0])
    return structure


def test_raise_if_invalid_raises_only_when_invalid() -> None:
    validate_bonds(ca_only_chain(4)).raise_if_invalid()
    with pytest.raises(GeometryError, match="Invalid bond geometry"):
        validate_bonds(broken_structure()).raise_if_invalid()


def test_report_slicing_and_ordering() -> None:
    report = validate_bonds(broken_structure())
    assert not report.ok
    assert report.of_kind("bond_length") == report.of_class("ca_ca")
    assert report.of_kind("missing_atom") == ()
    indices = [v.residue_indices[0] for v in report.violations]
    assert indices == sorted(indices), "violations are ordered by residue index"
    severity = [v.overshoot for v in report.by_severity()]
    assert severity == sorted(severity, reverse=True)
    assert report.worst is report.by_severity()[0]
    assert report.violating_residues == tuple(sorted(set(report.violating_residues)))


def test_summary_and_describe_carry_the_numbers() -> None:
    report = validate_bonds(broken_structure())
    summary = report.summary()
    assert "bonds checked" in summary
    assert "violations" in summary
    described = report.describe(max_violations=1)
    assert "ca_ca:" in described  # the deviation distribution
    assert "violations by kind" in described
    assert "more violation(s)" in described


def test_distribution_reports_per_class_statistics() -> None:
    report = validate_bonds(read_structure(DATA / "arf19.pdb"))
    distribution = report.distribution()
    assert set(distribution) == {"intra_residue", "peptide"}
    assert distribution["intra_residue"]["n"] == report.n_intra_checked
    assert distribution["peptide"]["n"] == report.n_peptide_checked
    assert 0.0 < distribution["intra_residue"]["p50"] < 0.05


def test_report_is_not_compared_by_numpy_arrays() -> None:
    """Check the report is hashable and comparable.

    A generated dataclass ``__eq__`` over numpy fields raises "truth value of an array is
    ambiguous", which is why the report sets ``eq=False``.
    """
    report = validate_bonds(ca_only_chain(4))
    assert isinstance(report, BondReport)
    assert report == report
    assert len({report}) == 1


def test_check_switches_turn_individual_checks_off() -> None:
    structure = read_structure(DATA / "dnmt3a.pdb")
    assert validate_bonds(structure, check_intra_residue=False).n_intra_checked == 0
    assert validate_bonds(structure, check_peptide=False).n_peptide_checked == 0
    assert validate_bonds(structure, check_intra_residue=False, check_peptide=False).ok
    only_ca = validate_bonds(
        structure, check_intra_residue=False, check_peptide=False, check_unexpected_contacts=False
    )
    assert only_ca.n_bonds_checked == only_ca.n_ca_ca_checked


@pytest.mark.parametrize(
    ("kwargs", "match"),
    [
        ({"tolerance_sigma": -1.0}, "tolerance_sigma must be positive"),
        ({"tolerance_sigma": float("nan")}, "tolerance_sigma must be finite"),
        ({"absolute_tolerance": float("inf")}, "absolute_tolerance must be finite"),
        ({"ca_ca_tolerance": 0.0}, "ca_ca_tolerance must be positive"),
    ],
)
def test_unusable_tolerances_raise(kwargs: dict[str, float], match: str) -> None:
    """A NaN threshold makes every comparison False, which disables a check instead of failing."""
    with pytest.raises(GeometryError, match=match):
        validate_bonds(ca_only_chain(4), **kwargs)  # type: ignore[arg-type]


def test_non_structure_input_raises() -> None:
    with pytest.raises(GeometryError, match="needs a Structure"):
        validate_bonds(np.zeros((4, 3)))  # type: ignore[arg-type]


def test_single_residue_structure_is_handled() -> None:
    report = validate_bonds(build([("GLY", glycine(), "A", 1)]))
    assert report.n_peptide_checked == 0
    assert report.n_ca_ca_checked == 0
    assert report.ok


# ---------------------------------------------------------------------------
# Calibration against the real fixtures
# ---------------------------------------------------------------------------

#: Measured violation counts on every fixture, unmodified, at the default tolerances.
#:
#: These are pinned so a tolerance change has to be deliberate. What each number is:
#:
#: arf19, dnmt3a, p300 -- AlphaFold models, which is what the reference was measured from and
#: what DODO is built for. arf19 is perfectly clean. dnmt3a's 3 findings are all one residue,
#: A:HIS613, whose imidazole ring is modelled with ND1-CE1 at 2.14 A instead of 1.33 A. p300's 22
#: are 8 residues with the same class of defect plus one MET whose CA-CB is 3.08 A.
#:
#: 6kn7 -- an experimental EM structure, and the reference is AlphaFold-derived. Its 287 findings
#: are 247 distinct residues (3.2% of them), overshooting the accepted window by a median of
#: 0.011 A and at most 0.119 A, dominated by aliphatic side-chain C-C bonds. That is the
#: systematic experiment-versus-prediction difference reference.py documents, not a bug.
#:
#: test.pdb -- not a protein: a 1.5 A-spaced point dump written as CA records by a pre-rewrite
#: debug path. 6,478 of its 7,990 virtual bonds are outside any plausible range, three of them
#: over 200 A. Reporting it as broken is correct.
#:
#: testing_translation.pdb -- pre-rewrite DODO output, and the only fixture with a mix of
#: all-atom and CA-only regions. Its 7 findings are the 4 real defects v2 exists to prevent (two
#: CA-CA bonds of exactly 0.000 A where a region was grafted onto the wrong anchor, and two of
#: 56.2 and 53.8 A where it flew off) plus the same HIS613 ring as dnmt3a, which it inherited.
FIXTURE_VIOLATIONS = {
    "arf19.pdb": 0,
    "dnmt3a.pdb": 3,
    "p300.pdb": 22,
    "6kn7.pdb": 287,
    "test.pdb": 6478,
    "testing_translation.pdb": 7,
}


@pytest.mark.parametrize("name", sorted(FIXTURE_VIOLATIONS))
def test_fixture_violation_counts_are_stable(name: str) -> None:
    report = validate_bonds(read_structure(DATA / name))
    assert len(report.violations) == FIXTURE_VIOLATIONS[name], (
        f"{name}: measured {len(report.violations)} violations, expected "
        f"{FIXTURE_VIOLATIONS[name]}.\n{report.describe(max_violations=5)}"
    )


def test_alphafold_fixtures_are_essentially_clean() -> None:
    """The usability bar: the flag rate on real input must be low enough to read.

    Measured over the three AlphaFold fixtures, 0.081% of 30,500 intra-residue and peptide bonds.
    A validator that flags a few percent of real structures is not usable, and that is what the
    naive symmetric-window and tighter-floor variants did (up to 4.0% on 6kn7).
    """
    checked = 0
    flagged = 0
    for name in ("arf19.pdb", "dnmt3a.pdb", "p300.pdb"):
        report = validate_bonds(read_structure(DATA / name))
        checked += report.n_intra_checked + report.n_peptide_checked
        flagged += len(report.violations)
    rate = flagged / checked
    assert rate < 0.002, f"flagged {flagged} of {checked} bonds ({100 * rate:.3f}%)"


def test_experimental_fixture_findings_are_small_and_local() -> None:
    """Check that the experimental fixture's findings are small and local.

    6kn7 flags more than the predicted fixtures do, and that is expected -- but the findings have
    to be individually small, which is real strain, rather than gross, which would be a broken
    structure or a broken validator.
    """
    report = validate_bonds(read_structure(DATA / "6kn7.pdb"))
    overshoot = np.array([v.overshoot for v in report.violations])
    assert overshoot.max() < 0.2, "no 6kn7 bond is grossly wrong, only strained"
    assert float(np.median(overshoot)) < 0.03
    assert len(report.violating_residues) / report.n_residues < 0.05
    assert report.of_kind("missing_atom") == ()
    assert report.of_kind("unexpected_contact") == ()
    assert report.of_kind("chain_break") == ()


def test_pdb_and_cif_of_the_same_structure_agree() -> None:
    """The two readers must produce geometry the validator cannot tell apart."""
    for stem in ("6kn7", "arf19", "p300"):
        from_pdb = validate_bonds(read_structure(DATA / f"{stem}.pdb"))
        from_cif = validate_bonds(read_structure(DATA / f"{stem}.cif"))
        assert from_pdb.n_bonds_checked == from_cif.n_bonds_checked, stem
        assert [v.message for v in from_pdb.violations] == [
            v.message for v in from_cif.violations
        ], stem


def test_findings_are_invariant_under_rigid_body_motion() -> None:
    """Check that the report does not change under rotation and translation.

    Bond lengths are rigid-body invariants and DODO moves folded domains rigidly, so if a rotation
    changes the report then the report is measuring something other than bond lengths.
    """
    structure = read_structure(DATA / "dnmt3a.pdb")
    before = validate_bonds(structure)
    rotation = Rotation.from_euler("xyz", [23.0, -47.0, 91.0], degrees=True).as_matrix()
    structure.rotate(rotation)
    structure.translate([137.0, -42.0, 9.5])
    after = validate_bonds(structure)
    assert after.n_bonds_checked == before.n_bonds_checked
    assert len(after.violations) == len(before.violations)
    for old, new in zip(before.violations, after.violations, strict=True):
        assert old.residue_labels == new.residue_labels
        assert old.atoms == new.atoms
        assert new.measured == pytest.approx(old.measured, abs=1e-6)


def test_every_fixture_finding_is_actionable() -> None:
    """Check that every finding names its residue, states its measurement and is a sentence.

    A finding a user cannot act on is noise, so this is checked over every real finding there is.
    """
    for name in sorted(FIXTURE_VIOLATIONS):
        report = validate_bonds(read_structure(DATA / name))
        for violation in report.violations:
            message = violation.message
            assert message.endswith("."), message
            assert message[0].isupper(), message
            for label in violation.residue_labels:
                assert label in message, message
            for atom in violation.atoms:
                assert atom in message, message
            if math.isfinite(violation.measured):
                assert f"{violation.measured:.3f}" in message, message
                assert violation.accepted_low is not None or violation.accepted_high is not None


def test_whole_assembly_is_fast_enough() -> None:
    """Check the whole 61,511-atom assembly validates quickly.

    Measured at 27 ms, mean of five runs. The bound asserted is loose so that a slow machine does
    not fail the suite, but an accidental O(n^2) would blow straight through it.
    """
    structure = read_structure(DATA / "6kn7.pdb")
    validate_bonds(structure)  # warm the caches so this measures the algorithm
    start = time.perf_counter()
    report = validate_bonds(structure)
    elapsed = time.perf_counter() - start
    assert report.n_bonds_checked == 62548
    assert elapsed < 2.0, f"validating 6kn7 took {elapsed:.2f} s"


# ---------------------------------------------------------------------------
# Fresh rebuild output
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def rebuilt_dnmt3a() -> list[Structure]:
    import dodo

    report = dodo.rebuild(DATA / "dnmt3a.pdb", n_models=2, seed=20240617, backbone=False)
    assert report.ok, report.summary()
    return list(report.models)


def test_rebuild_output_introduces_no_bond_defects(rebuilt_dnmt3a: list[Structure]) -> None:
    """The real acceptance test. Every finding on rebuilt output must be inherited from the input.

    Measured: 3 findings per model, all of them A:HIS613's broken imidazole ring, all in a folded
    domain DODO only moved as a rigid body -- and a rigid-body move cannot change an
    intra-residue distance. Nothing is attributed to a rebuilt region.
    """
    for model in rebuilt_dnmt3a:
        report = validate_bonds(model)
        assert report.of_provenance("rebuilt") == (), report.describe()
        assert report.of_kind("missing_atom") == (), report.describe()
        assert report.of_kind("chain_break") == (), report.describe()
        assert report.of_kind("unexpected_contact") == (), report.describe()
        assert {v.residue_labels[0] for v in report.violations} == {"A:HIS613"}


def test_rebuilt_regions_are_ca_only_and_pass_their_ca_ca_check(
    rebuilt_dnmt3a: list[Structure],
) -> None:
    for model in rebuilt_dnmt3a:
        report = validate_bonds(model)
        assert report.n_ca_only_residues > 300, report.summary()
        assert report.n_ca_ca_checked > 300, report.summary()
        assert report.of_class("ca_ca") == (), report.describe()
        # And they are built tightly, not merely within tolerance.
        worst = float(np.abs(report.ca_ca_deviations).max())
        assert worst < DEFAULT_CA_CA_TOLERANCE / 2.0, f"worst CA-CA deviation {worst:.4f} A"


def test_rebuild_output_is_measured_not_assumed(rebuilt_dnmt3a: list[Structure]) -> None:
    """Pin what the deviation distribution of rebuilt output actually looks like.

    A regression in the builder then shows up as a shifted distribution rather than as a silent
    pass, which is what a bare ``assert report.ok`` would give.
    """
    report = validate_bonds(rebuilt_dnmt3a[0])
    stats = report.distribution()
    assert stats["ca_ca"]["p99"] < 0.05, stats["ca_ca"]
    assert abs(stats["intra_residue"]["mean"]) < 0.01, stats["intra_residue"]
